name: ci-main

on:
  push:
  pull_request:
  schedule:
    - cron: "11 3 * * 6"

jobs:
  test:
    if: success() || failure()

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [clang, gcc]
        os: [ubuntu-latest, macos-latest]
        varnish: ['6.0', '7.4', '7.5']

    steps:
    - uses: varnishcache-friends/setup-varnish@v1
      with:
        version: ${{ matrix.varnish }}
    - run: |
        sudo apt-get update
        sudo apt-get install -y python3-docutils libmaxminddb-dev
      if: runner.os == 'Linux'
    - run: brew install automake docutils libmaxminddb
      if: runner.os == 'macOS'
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: ./autogen.sh
    - run: CC=${{ matrix.compiler }} ./configure CFLAGS="-Wall -Wextra -Werror"
    - run: make
    - run: make check VERBOSE=1
